import Head from 'next/head'
import styles from '../src/styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>This is a test</h1>
      <p className={styles.code}>Should work</p>
    </div>
  )
}
